- name: Build health list (Linux)
  ansible.builtin.set_fact:
    _health_cmds: >-
      {{
        phase_services | map(attribute='containers') | sum(start=[])
        | map(attribute='serviceCommands') | select('defined')
        | map(attribute='health') | reject('equalto', None)
        | map('trim') | reject('equalto','') | list
      }}

- block:
    - name: (check) would health-check (Linux)
      ansible.builtin.debug: { var: _health_cmds }

    - name: Push simulated health summary (Linux)
      ansible.builtin.set_fact:
        start_health_summary: "{{ (start_health_summary | default([])) + [ {'component': 'all', 'start_fail': false, 'health_fail': false} ] }}"
      when: ansible_check_mode | default(false)

- block:
    - name: Health check (Linux)
      ansible.builtin.shell: "{{ item }}"
      args: { executable: /bin/bash }
      loop: "{{ _health_cmds }}"
      register: _health_out
      failed_when: false
      changed_when: false

    - name: Build failed health details
      ansible.builtin.set_fact:
        _failed_health_details: >-
          {{ [ {'item': r.item, 'rc': r.rc, 'stdout': (r.stdout | default('')) | trim, 'stderr': (r.stderr | default('')) | trim} for r in (_health_out.results | default([]) | rejectattr('rc','eq',0) | list) ] }}
      when: (_health_out.results | default([]) | rejectattr('rc','eq',0) | list | length) > 0

    - name: Debug failed health checks (rc/stdout/stderr)
      ansible.builtin.debug:
        var: _failed_health_details
      when: _failed_health_details is defined and _failed_health_details | length > 0

    - name: Fail if any health checks failed
      ansible.builtin.fail:
        msg: >-
          Health failures detected on {{ inventory_hostname }}:
          {{ _failed_health_details | map(attribute='item') | join(' | ') }}
      when: _failed_health_details is defined and _failed_health_details | length > 0

    - name: Push health summary (Linux)
      ansible.builtin.set_fact:
        start_health_summary: >-
          {{ (start_health_summary | default([])) + [ {'component': 'all', 'start_fail': false, 'health_fail': (_health_out is defined and (_health_out.results | default([]) | selectattr('rc','defined') | selectattr('rc','ne',0) | list | length) > 0) | bool } ] }}
      when: not (ansible_check_mode | default(false))
